# Generated by Django 3.2.24 on 2024-02-25 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price_range', models.CharField(choices=[('$', 'Very Cheap'), ('$$', 'Cheap'), ('$$$', 'Moderate'), ('$$$$', 'Expensive'), ('$$$$$', 'Very Expensive')], default='$$$', max_length=10)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('url', models.URLField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('hours', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='business',
            field=models.ManyToManyField(to='reviews.Business'),
        ),
        migrations.AddField(
            model_name='review',
            name='business',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reviews.business'),
        ),
    ]
